# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode #unicode
  database: cptcambio
  #host: localhost
  #pool: 5
  username: ubuntu # krobellus #ubuntu 
  password: password #Xatm@074 #password 

test:
  adapter: postgresql
  encoding: unicode #unicode
  database: cptcambio
  #host: localhost
  #pool: 5
  username: ubuntu #krobellus #ubuntu 
  password: password #Xatm@074 #password 